[project]
site_name = "Awesome Research Guides"
description = "Research guides offer guidance about conducting scientific research."
version = "1.0.0"
docs_dir = "docs"
extra_css = ["style.css"]
[project.theme]
features = [
  "navigation.top"
]
#logo = "media/icon.svg"
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"