---
title: "Awesome Research Guides"
author: "Neea Rusch and contributors"
fontsize: 11pt
papersize: letter
documentclass: scrartcl
# macOS: brew install --cask font-liberation
mainfont: Liberation Sans
sansfont: Liberation Sans
linestretch: 1.25
geometry: margin=1truein, truedimen, twoside=false, ignoreall
header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{microtype}
  - \usepackage{etoolbox}
  - \usepackage{scrlayer-scrpage}
  - \pagestyle{scrheadings}
  - \usepackage{flushend}
  - \makeatletter\patchcmd{\@maketitle}{\huge}{\LARGE}{}{}\makeatletter
  - \setkomafont{author}{\large}
  - \ifoot{\small\href{https://guides.neea.pl}{guides.neea.pl}}
---