---
title: "Awesome Research Guides"
author: "Neea Rusch"
subject: "scientific research"
fontsize: 11pt
papersize: letter
documentclass: scrartcl
mainfont: Liberation Sans
sansfont: Liberation Sans
linestretch: 1.25
geometry: margin=1truein, truedimen, twoside=false, ignoreall
cover-image: tmp/cover.jpg
epub-title-page: false
toc-title: "Contents"
header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage{geometry}
  - \usepackage{graphicx}
  - \usepackage{microtype}
  - \usepackage{etoolbox}
  - \usepackage{bookmark}
  - \usepackage{scrlayer-scrpage}
  - \usepackage{flushend}
  - \usepackage{letltxmacro}
  - \pagestyle{scrheadings}
  - \setkomafont{subtitle}{\small}
  - \setkomafont{author}{\small}
  - \makeatletter\patchcmd{\@maketitle}{\huge}{\LARGE}{}{}\makeatletter
  - \ohead{\scriptsize\@title{ }• \@subtitle}
  - '\newcommand{\credit}[1]{{\par\scriptsize #1\par}}'
  - | # title page layout
        ```{=latex}
        \pretocmd{\tableofcontents}{\hypertarget{tableofcontents}{}\bookmark[level=section,dest=tableofcontents]{Contents}}{}{}
        \usepackage{geometry,bookmark,etoolbox}
        \let\oldmaketitle\maketitle
        \renewcommand{\maketitle}{
          \begin{titlepage}
          \newgeometry{margin=0pt}
          \noindent\includegraphics[width=\paperwidth,height=\paperheight]{tmp/cover.jpg}
          \restoregeometry
          \end{titlepage}
          \clearpage\thispagestyle{plain}
          \vspace{4em}
          \makeatletter
          {\@title\par}\vspace{1em}{\scriptsize\@subtitle\par}
          \makeatother
          {\scriptsize\input{tmp/credits.txt}}  
        \clearpage          
        }
        ```
---