---
title: "Awesome Research Guides"
author: ""
nocite: "[@*]"
fontsize: 11pt
papersize: letter
documentclass: scrartcl
mainfont: Liberation Sans
sansfont: Liberation Sans
linestretch: 1.25
geometry: margin=1truein, truedimen, twoside=false, ignoreall
header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{microtype}
  - \usepackage{etoolbox}
  - \makeatletter\patchcmd{\@maketitle}{\huge}{\LARGE}{}{}\makeatletter
---