name: Docs
on:
  push:
    branches : [ main ]
    paths:
      - readme.md
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'site'
      - if: github.event_name == 'push'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions-bot@users.noreply.github.com"
          git fetch origin main
          git checkout site || git checkout -b site origin/site          
          git merge origin/main --no-edit || {
            echo "Merge conflict detected. Manual intervention required."
            exit 1
          }
          git push origin site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: git-sync
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install zensical
      - run: bash prep.sh
      - run: zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment