name: Test
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - "references/*"

jobs:
  test_build:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CONTAINER }}
      options: --platform linux/amd64
    steps:
      - uses: actions/checkout@v7
      - run: make docs
      - run: zensical build --clean