name: Test
on:
  push:
    branches:
      - main
    paths:
      - readme.md
  pull_request:
    paths:
      - readme.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        if: ${{ github.event_name != 'pull_request' }}
      - uses: actions/checkout@v6
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0
      - name: Check lint
        run: npx awesome-lint

      - name: Extract change
        run: |
          set -o pipefail
          git diff --unified=0 --no-prefix --output-indicator-new=% origin/main...HEAD -- readme.md | sed -n 's/^%//p' > ./checkme.md

      - name: Check URL status
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          args: '--exclude ${{ vars.URL_EXCLUDES }} --accept ${{ vars.URL_ACCEPT }} checkme.md'
          fail: github.event_name != 'pull_request'
          failIfEmpty: false
          output: ./lychee.md

      - name: Collect report
        if: ${{ github.event_name == 'pull_request' }}
        id: infos
        run: |
          if [ -s "./lychee.md" ]; then
            CONTENT=$(cat "./lychee.md" | tr '\n' '\r' | sed -e 's/\r/\\n/g')
          else
            CONTENT="No "
          fi          
          CONTENT=$(echo "$CONTENT" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')          
          echo "result=$CONTENT" >> $GITHUB_OUTPUT

      - name: Report in comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v9
        env:
          RESULT: ${{ steps.infos.outputs.result  }}
        with:
          script: |
            const body = `### Check results\n\n${(process.env.RESULT || "").trim()}`            
            const identifier = "<!-- quality-comment -->";
            const commonPayload = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `${identifier}\n${body}`,        
            }   
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });                 
            const existing = comments.find(c => c.body.includes(identifier));
            if (existing)
              await github.rest.issues.updateComment({ comment_id: existing.id, ...commonPayload });
            else 
              await github.rest.issues.createComment({ issue_number: context.issue.number, ...commonPayload });

      - if: ${{ github.event_name == 'pull_request' && steps.lychee.outputs.exit_code != '0' }}
        run: echo "URL check failed" && exit 1
