name: URL check

on:
  schedule:
    - cron:  '0 9 * * 1' # weekly
  pull_request:
    paths:
      - .github/workflows/urls.yml
  workflow_dispatch:

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: lycheeverse/lychee-action@v2
        with:
          args: '--timeout 60 --exclude ${{ vars.URL_EXCLUDES }} --accept ${{ vars.URL_ACCEPT }} --host-stats readme.md'
          fail: true


