name: URL Status

on:
  schedule:
    - cron:  '0 6 * * 1'  # Mondays 06:00
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/urls.yml

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: lycheeverse/lychee-action@v2
        with:
          args: '--exclude ${{ vars.URL_EXCLUDES }} --accept ${{ vars.URL_ACCEPT }} --host-stats readme.md'
          fail: true


