name: URL Status

on:
  schedule:
    - cron:  '0 6 * * 1'  # Mondays 06:00
  workflow_dispatch:

jobs:
  check-urls:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: lycheeverse/lychee-action@v2
        with:
          args: |
            readme.md
            --exclude ${{ vars.URL_EXCLUDES  }}
            --accept ${{ vars.URL_ACCEPT  }}
            --host-stats
          fail: true


